blank_issues_enabled: false
contact_links:
  - name: Discussion / question
    url: https://github.com/Pieter-OHearn/quro/discussions
    about: For general questions and discussion, please use GitHub Discussions.
